networks:
  hispanie_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 169.254.10.0/24

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      hispanie_bridge:
        ipv4_address: 169.254.10.2
        aliases:
          - "hispanie-backend.app"
    ports:
      - 3201:3201
    volumes:
      - ./:/app/
      - /app/hispanie.egg-info/
    depends_on:
      postgres:
        condition: service_healthy

  # TODO fix container name to use postgres-service as in hispanie.ini config file
  postgres:
    image: postgres:17.1-alpine
    networks:
      hispanie_bridge:
        ipv4_address: 169.254.10.3
        aliases:
          - "hispanie-backend.db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgsql/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
